# Generated by Django 4.2 on 2023-05-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
    ]
