# Generated by Django 4.2 on 2023-05-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteBase', '0002_remove_blog_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
