# Generated by Django 4.2 on 2023-05-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteBase', '0003_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount',
            name='last_ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hitcount',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
