# Generated by Django 4.2 on 2023-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteBase', '0004_hitcount_last_ip_address_hitcount_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, unique=True)),
                ('last_visited', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hitcount',
            name='last_ip_address',
        ),
        migrations.AddField(
            model_name='hitcount',
            name='ip_addresses',
            field=models.ManyToManyField(to='siteBase.ipaddress'),
        ),
    ]
