# Generated by Django 4.2 on 2023-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteBase', '0005_ipaddress_remove_hitcount_last_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('metatag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField()),
                ('body', models.TextField()),
                ('date_made', models.DateField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='siteBase.tag')),
            ],
        ),
    ]
